name: Multi-Language CI & Versioning

on:
  push:
    tags:
      - 'v*'    # version tags like v1.0.0
  pull_request:
    branches: [ main ]

jobs:

  versioning:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Extract version from tag
        id: get_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT

  build-python:
    runs-on: ubuntu-latest
    needs: versioning
    defaults:
      run:
        working-directory: python-service
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - run: pip install -r requirements.txt
      - run: pytest

  build-go:
    runs-on: ubuntu-latest
    needs: versioning
    defaults:
      run:
        working-directory: go-service
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.21
      - run: go build -v .

  build-java:
    runs-on: ubuntu-latest
    needs: versioning
    defaults:
      run:
        working-directory: java-service
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - run: javac Main.java

  build-rust:
    runs-on: ubuntu-latest
    needs: versioning
    defaults:
      run:
        working-directory: rust-service
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo build --release

        - name: Build Docker image
  run: docker build -t dhananjayshk39/python-service:${{ needs.versioning.outputs.version }} .

    - name: Login to Docker Hub
  uses: docker/login-action@v3
  with:
    username: ${{ secrets.DOCKER_USERNAME }}
    password: ${{ secrets.DOCKER_PASSWORD }}


